### ISSUE TITLE
Browser Extension Support 

### ISSUE THREAD

**Issue by Raul1198** [giantpinkrobots/varia#10]
Since Varia uses aria2 is there anyway to use aria2 browser extension to capture download automatically like motrix

**Comment by lamyergeier** [comment]
@giantpinkrobots So if one wants to use the extension, they should copy paste the URL in the extension, right? There is no way currently for it to capture download request  from Firefox right?

**Comment by giantpinkrobots** [comment]
A very simple extension for Chromium and Firefox will be available with the next version (hopefully - if everything goes smoothly).

![variaChromeScreenshot](https://github.com/giantpinkrobots/varia/assets/93845996/99cf2708-c905-4ed9-8cb9-65fb1a55d589)

Right now the extension I've written allows the browser to intercept the download and send them to the aria2c daemon.

**Comment by candrapersada** [comment]
Is there Referrer support?
`--referer=<REFERER>`

**Comment by giantpinkrobots** [comment]
It just intercepts downloads and sends the url to aria2c through RPC with the "addUri" function if enabled. Nothing else. As this is the first extension I've hacked together, it's very simple right now.

**Comment by giantpinkrobots** [comment]
The browser extension support has been released (v2024.2.29) and is now usable (v2024.2.29-2). You can download the extension for Firefox or Chrome/ium from their extension stores.
