### ISSUE TITLE
Feature request: close to background

### ISSUE THREAD

**Issue by lordekeen** [giantpinkrobots/varia#114]
Since it looks like the app can't use the system tray, but works fine in the background, would be nice if the close button (or minimize) could return the app to the background instead of closing it (this behavior could be set in preferences). Going the same route, add the option to auto close to background when download finishes.

**Comment by N0tACyb0rg** [comment]
I am actually working on a fix for this issue in #104 if you would like to check that out (it uses PyQt6).
