### ISSUE TITLE
Can't add torrent

### ISSUE THREAD

**Issue by forteller** [giantpinkrobots/varia#118]
Hi. I don't understand how to open a torrent file with Varia. Drag-n-drop from Nautilus does not work, an there is no way to do it via the hamburger menu. Downloading the torrent file trough Varia does not open it with Varia either.

Is this a bug, or am I missing something? Thanks!

v2024.5.7

Thanks!

**Comment by superuser-miguel** [comment]
I would use Deluge or Fragments instead for that. You get far more features from a proper torrent client.

**Comment by forteller** [comment]
Ok, but Varia says it's supposed to support torrents

**Comment by giantpinkrobots** [comment]
Downloading the .torrent file through Varia should do it. Either by entering the URL manually and pressing Download, or through the browser extension. So I don't know what went wrong there. But I also added a new button to open .torrent files in the commit d63739d6dbc914f6177806a26c732f4f112cc5e9 and it should land in the next version, fixing this issue completely.
