### ISSUE TITLE
Feature request: support connecting to existing `aria2c` daemon

### ISSUE THREAD

**Issue by waltmck** [giantpinkrobots/varia#128]
I use `aria2c` as a systemd service, which I can then interact with using an RPC client such as [this project](https://github.com/pawamoy/aria2p). This is nice for a couple reasons: I can remotely manage downloads for a headless server over a VPN, and downloads are automatically continued and run the the background when the computer boots (without any GUI components needing to load).

You have a very nice GUI and you already run an `aria2c` instance internally, so why not allow connection to a daemon running in a separate process? This would be similar in spirit to to [transmission-remote](https://github.com/transmission-remote-gtk/transmission-remote-gtk).

It would also allow more granular configuration by editing the `aria2.conf` file, giving power-users [desired customization ability](https://github.com/giantpinkrobots/varia/issues/30#issue-2033261436) without cluttering the settings GUI.

**Comment by giantpinkrobots** [comment]
Hello. Connecting to a remote aria2c daemon has been supported for a while now, but on the latest version apparently I accidentally removed the option in the Preferences page and somehow didn't notice. I'm very professional as you can see.

I re-added the option in the commit 751c858ac45aa608f49c927c6557ef650402c0d1 and it will be made available in the next version which I plan to release soon. Until that you can build the next branch to use this feature. It'll be under Advanced Settings.

![resim](https://github.com/user-attachments/assets/09827d67-74c8-4eb6-b04f-9e39578aff7f)

**Comment by Thesola10** [comment]
is there an ETA for a Flatpak release shipping this fix? thanks for the hard work btw

**Comment by giantpinkrobots** [comment]
> is there an ETA for a Flatpak release shipping this fix? thanks for the hard work btw

[Now.](https://github.com/giantpinkrobots/varia/releases/tag/v2024.11.7)
