### ISSUE TITLE
Keyword "bittorrent" missing in metadata

### ISSUE THREAD

**Issue by ztefn** [giantpinkrobots/varia#134]
Just a little heads up: When i searched for the term "bittorrent" [on Flathub](https://flathub.org/apps/search?q=bittorrent) i was surprised to find out that Varia didn't show up.

I think it would be helpful to include this term somewhere in the metadata, for example as [keyword in the desktop file](https://github.com/giantpinkrobots/varia/blob/v2024.11.7-1/data/io.github.giantpinkrobots.varia.desktop.in#L11).

**Comment by giantpinkrobots** [comment]
You're right, just added it now. Next version will have it. Thanks for the heads up.
