### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [giantpinkrobots/varia#2]
It would be great if this app could be translated. If you implement this, I will provide the Dutch translation. 🙂

**Comment by daPhipz** [comment]
I'll be working on the German translation!

**Comment by sabriunal** [comment]
https://github.com/giantpinkrobots/varia/pulls

Some chores complated. gettext binding should be implemented.

**Comment by sabriunal** [comment]
![resim](https://github.com/giantpinkrobots/varia/assets/6218679/345c2aac-75d5-4f2a-90ff-a5659459852c)

**Comment by sabriunal** [comment]
Translation support is ready. 

@giantpinkrobots could you please close the issue.

**Comment by giantpinkrobots** [comment]
The translation support is here, but please wait until my next commit before starting the translations, since I have added a few more snippets of text. Thank you all!
