### ISSUE TITLE
Improve app summary

### ISSUE THREAD

**Issue by bragefuglseth** [giantpinkrobots/varia#24]
Flathub's [quality guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/) for app metadata says these things about summaries:

> Starting summaries with an article is almost always unnecessary. Instead, either omit the article or **ideally phrase it in the imperative with a verb.**

> The summary should be understandable by a non-technical person, and not contain any technical terms. Don't mention the toolkit, programming language, or other implementation details that would not be relevant to a non-developer and explain what the app does for people instead.

Based on this, the summary would be more in line with the guidelines if it was changed from "Download manager based on aria2" to e.g. "Download files efficiently".

**Comment by giantpinkrobots** [comment]
You're right. I have changed it to "Download files quickly and efficiently", and I will focus more on the app metadata before the next release. Thanks for the heads up.
