### ISSUE TITLE
Preferences window cleanups

### ISSUE THREAD

**Issue by bragefuglseth** [giantpinkrobots/varia#27]
For reference, this is how the preferences window currently looks :slightly_smiling_face: 

![Skjermbilde fra 2023-12-08 17-25-54](https://github.com/giantpinkrobots/varia/assets/91388039/c48121fe-8311-48f2-a140-d206f37ba61c)

Some suggestions:

- [x] Make it transient for the main window so it's attached to it
- [ ] Make the speed limit row an AdwSpinRow and settle on a single sensible unit instead of asking people to make the decision
- [x] Make the username and password rows AdwEntryRows, and use the built-in confirmation button of the entry row instead of having one at the bottom
- [x] Disable the search button because of the low amount of preferences

**Comment by giantpinkrobots** [comment]
![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/cf16321e-b82c-4f34-a4f2-476eb38c6c13)

Hello, I have followed through with three of your suggestions, and I think it does look better. But with the second suggestion, I hard disagree. I think being able to select between units is much better. Okay, maybe being able to select GB/s is a bit useless, but I think the KB/s and MB/s options can be very useful. Therefore I definitely want to have them.

Thank you for your suggestions! I am closing this now as completed.
