### ISSUE TITLE
Is there any Installation guide without using flatpak?

### ISSUE THREAD

**Issue by denisgolius** [giantpinkrobots/varia#3]
Hello!
Could you please add an instruction for users who don't want to use flatpak?  I mean something like:
```
git clone (https://github.com/giantpinkrobots/varia.git
cd varia
install meson
run meson build...
```

**Comment by giantpinkrobots** [comment]
I have added a 'Building' section to the README. Thanks for the suggestion.

**Comment by giantpinkrobots** [comment]
The build instructions were broken, so I removed them and I am reopening this issue to serve as a reminder to fix the code to support non-Flatpak building.

**Comment by rpedrica** [comment]
Thank you very much for the info; I'll have a go at adapting the Arch script. Looks very similar to what I've done but there are some small important items there that could resolve my issue.

Thank you and regards, Robby

**Comment by denisgolius** [comment]
> Building from source guide is officially here, and it works. Thank you all for waiting.

Thanks you!
