### ISSUE TITLE
Add "Clear All Downloaded" to Hamburger menu

### ISSUE THREAD

**Issue by superuser-miguel** [giantpinkrobots/varia#33]
Adding this as an enhancement. 

A option to "Clear All Downloaded" option in the Hamburger Menu, to avoid issues with cluttered main area. See below.
![2024-01-03_13-07-59](https://github.com/giantpinkrobots/varia/assets/16271056/8b1a1c79-cd9e-43e0-b9a0-057b88ea9c22)

The option would be in the Hamburger menu : 
![2024-01-03_13-10-00](https://github.com/giantpinkrobots/varia/assets/16271056/14a67d37-cad2-444a-ab43-3d46b9595c88)

Would allow to continue using the application as you work on other downloads.

**Comment by giantpinkrobots** [comment]
![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/e81a6968-8e95-4425-b856-53ddea9c9534)

You're right, it looks better this way and is less cluttered. Will be added with the next version. Thanks!
