### ISSUE TITLE
Enhancement : Allow Download to other locations

### ISSUE THREAD

**Issue by superuser-miguel** [giantpinkrobots/varia#35]
Currently downloads default to `/home/<User>/Downloads` As an enhancement, allowing for a call to Portal and the File manager to download to a different location.

**Comment by giantpinkrobots** [comment]
That feature exists, in the settings menu. Maybe you're on an older version?

**Comment by superuser-miguel** [comment]
![2024-01-03_17-36-07](https://github.com/giantpinkrobots/varia/assets/16271056/8c61334c-6a5d-47ce-8e8e-a5f10190ea59)

Got it, Thanks Please close.
