### ISSUE TITLE
"Pause all" doesn't seem to work properly

### ISSUE THREAD

**Issue by ThatOneCalculator** [giantpinkrobots/varia#36]
- When clicking "Pause all", only the first download pauses
- After manually pausing all downloads, it **should** turn into a "Resume all" button, but stays as "Pause all"

![image](https://github.com/giantpinkrobots/varia/assets/44733677/f4753615-b646-44b6-9759-befd030676c2)

**Comment by giantpinkrobots** [comment]
Thanks for notifying. I will look into these, but I have a ton of schoolwork and finals approaching, so I really shouldn't right now. Once those are all done I plan on tackling the issues.
