### ISSUE TITLE
Support remote instance of Aria

### ISSUE THREAD

**Issue by Froggy232** [giantpinkrobots/varia#51]
Hi,
First, thanks you for your app!
Have you plan to add an option to connect the app to a remote instance of aria?
I think it would be very usefull, but I don't know if it would be easy to implement.
Thanks you!

**Comment by giantpinkrobots** [comment]
I really like that idea, and yes, I managed to get it working.

![image](https://github.com/giantpinkrobots/varia/assets/93845996/7976c780-d431-4b88-a234-1e0ac8ff3770)

Needs more testing tho of course.

**Comment by Froggy232** [comment]
Nice, thanks you a lot!!!
Do you have an idea for a release date? I will switch to varia as soon as it's available.
Thanks you

**Comment by giantpinkrobots** [comment]
It is available on the next branch right now, so you can clone that and build it with GNOME Builder to use it, but I don't have a full release date. Up until this point I made releases pretty frequently and I want to move away from that, it leads to not-very-substantial updates and lack of testing, also makes the lives of translators hard.

**Comment by Froggy232** [comment]
I understand, thanks you again.

**Comment by giantpinkrobots** [comment]
This feature has been released with the newest update. Closing.
