### ISSUE TITLE
Buggy behaviour with app

### ISSUE THREAD

**Issue by bungadrum** [giantpinkrobots/varia#54]
When you run the app it always opens and positions itself in the upper left corner of the screen. You move it to the center and close it in hope that it will remember that position, but when you run it again it still opens in the upper left corner of the screen. If you make it fullscreen and close it and then reopen it will not remember that it was in fullscreen it will still reopen in the upper left corner of the screen. Can you please fix this behaviour having to open reposition it every time you run it or maximizing it is a pain. Also CTR-Q or CTR-W doesn't close it you always have to click the X button can you add that option as well.

**Comment by giantpinkrobots** [comment]
Hello. This is the desktop environment's behavior, if you're using Gnome you can use the Gnome Tweaks app to change it.

**Comment by bungadrum** [comment]
I am using XFCE

**Comment by giantpinkrobots** [comment]
I don't use XFCE, but from what I see from a Reddit post you can tweak it this way:
[settings > window manager tweaks > placement](https://www.reddit.com/r/xfce/comments/scf53e/comment/hu5qk5w/)

**Comment by bungadrum** [comment]
I will check it out tnx

**Comment by giantpinkrobots** [comment]
Alright, closing this issue.
