### ISSUE TITLE
App doens't launch since last update

### ISSUE THREAD

**Issue by Froggy232** [giantpinkrobots/varia#59]
Hi,
Since the today's update, varia doesn't launch anymore.
If I try to launch it from the terminal, it tell me that : 
```
/app/share/varia/../../bin/aria2c: unrecognized option '--follow-torrent=mem'
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.
```
I have tried to reset the flatseal right and to remove the .var/app folder, but it didn't change anything.
Thanks you!

**Comment by bungadrum** [comment]
Have the same problem after latest update won't launch gives you loading animation, but never opens

**Comment by Raul1198** [comment]
+1 same error

**Comment by giantpinkrobots** [comment]
This issue was solved with the newest update. Closing.
