### ISSUE TITLE
Repetitive download of the file

### ISSUE THREAD

**Issue by wada3n** [giantpinkrobots/varia#62]
Hi,
When using the new Varia Chrome extension (Vivaldi), the app starts a **continuous** and **repetitive** download of the file. It seems like the extension keeps sending the link to the application even after the download has started.

[Varia.webm](https://github.com/giantpinkrobots/varia/assets/13304792/3dd3715a-e8d3-4ea4-88e9-a10048ad3e80)

**Comment by giantpinkrobots** [comment]
This is an issue I've encountered during the development of this version, but I thought I had fixed it. I have checked and it doesn't seem to be a problem with the extension itself, rather Varia itself fails to properly check if the download in the aria2 backend already exists within the UI.

**Comment by giantpinkrobots** [comment]
The issue has been fixed with the new v2024.2.29-2 hotfix. It will be available on Flathub by evening I think. Closing the issue.
