### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by lapor-kris** [giantpinkrobots/varia#68]
First, thanks for the app.
I cannot download anything from Nextcloud server. I use several Nextcloud servers, but I cannot download anything from them via the app. I get Authorization failed.
Is this a bug or is it not possible to implement?

Thanks

**Comment by giantpinkrobots** [comment]
Hi. Varia does support Basic Auth. Can you add your Nextcloud username and password into the Authentication section in Preferences? It should work then.

**Comment by lapor-kris** [comment]
Thanks for the tip. I tried with Authentication, but I still get Authorization failed.

**Comment by giantpinkrobots** [comment]
Are you using an app password?

**Comment by lapor-kris** [comment]
Sorry for late reply. No, I am using username and password for my Nextcloud instance. What exactly is an app password? Password for app Varia?
Thanks

**Comment by giantpinkrobots** [comment]
No, an app password is a password you can create in the settings page in Nextcloud. It's something you have to do if you're using two factor authentication.

**Comment by lapor-kris** [comment]
Thank you for clarifying it. No, I don't use the two factor authentication.

**Comment by giantpinkrobots** [comment]
Then it seems the basic auth support is not enough.

I'm actually currently experimenting with cookies.txt support in Varia. This way you can export your cookies from your browser (using something like [this](https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/)) and import that file to Varia. As long as the server can authenticate through the cookies, basic auth won't be needed. This means Varia can use any download link from any cloud provider as long as the user was logged onto it.

I think this feature would be great for your use case.

**Comment by giantpinkrobots** [comment]
Cookies.txt import support was added with v2024.5.7. Using a browser extension to export cookies of a Nextcloud login and importing that file into Varia now enables the ability to download files through Nextcloud. Thus this issue has been fixed for a while now, therefore closing. If another problem regarding this were to arise feel free to write again.
