### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by wada3n** [giantpinkrobots/varia#7]
Is it possible to create and schedule several download queues for downloading?

I think the best solution was previously implemented in Ugetdm , by days and hours.
![Skeduler](https://github.com/giantpinkrobots/varia/assets/13304792/38862cd6-5081-467e-bce1-8b50d53897e0)

In practice, the ability to run the program in the background should be added, especially after it was adopted in new versions of GNOME

**Comment by giantpinkrobots** [comment]
As Varia now has a background mode I will revisit this idea.

**Comment by giantpinkrobots** [comment]
A scheduler function was added with the commit [26e397f4dce0806098c124fba5037bab22cf648f](https://github.com/giantpinkrobots/varia/commit/26e397f4dce0806098c124fba5037bab22cf648f)

**Comment by giantpinkrobots** [comment]
Released with v2024.5.7.
