### ISSUE TITLE
feature: Add silent autostart option

### ISSUE THREAD

**Issue by fiftydinar** [giantpinkrobots/varia#70]
It would be nice if you can just not worry if Varia launched or not when you want to download something.
"Silent" indicates that app would launch in Background, instead of being presented to you as a window.

When this option would be enabled, clicking on X (Quit) button would also set the app in background (Instead of clicking separate "Background Mode"). Although, separation makes some sense still.

Developer of Fragments did not implement this due to not wanting users to trigger some legal action & wanting to make user more aware of when network transfer from Fragments stopped:
https://gitlab.gnome.org/World/Fragments/-/issues/30#note_1909051

My opinion on this:
1. That's the user responsibility on how much & which data they download. I understand that developer wants to avoid potential responsibility handed to him, but I believe this can be also solved by making a warning related to that at the 1st start of the app.
2. I believe this is a valid concern, but I think that this can be solved by intuitively indicating users that they can quit the app in Backgrounds section.
3. I don't agree with his app usage suggestions, as apps in overview are shown when you actively using it, while Backgrounds app portal is perfectly suitable for passive applications like download manager, where you just let stuff download. With his suggestions, window would always get out of your way, as you don't want to interact with it & it noticeably causes workflow annoyance.
4. It would encourage users more to seed torrents, since initial torrent support is added in latest version. Seeding torrents is a known good practice. It would avoid users accidentally quitting the app, where seeding would be interrupted.

**Comment by giantpinkrobots** [comment]
I think the X button should stay as it is, shutting the app down when clicked. But an option to make the app launch directly in background mode can be a useful feature.

Felix's argument on this kind of feature in a torrent client is valid I think, however imo that shouldn't impede the development of new potentially useful features. If someone is downloading stuff that may get them in trouble - rightfully or not - ultimately the burden is not on the tool that allowed them to do so.

**Comment by giantpinkrobots** [comment]
Starting in background mode will be available in the next version.

**Comment by giantpinkrobots** [comment]
Released with v2024.5.7.
