### ISSUE TITLE
feature: Suspend / Shutdown when active download has finished.

### ISSUE THREAD

**Issue by lomapur** [giantpinkrobots/varia#77]
Hello!

First of all, thank you for your work on Varia, looks like a useful project!

Varia version: v2024.2.29-2

One feature I would really need for Varia to be useful for me though (or at least more useful thank simple downloading via the browser) would be a possibility to suspend or shutdown my computer after the download is done.

What my use case is is that sometime I start bigger downloads in the evening/night (mobile data cap during the day...) and I leave my laptop to download the file while I go to sleep - unfortunately this means if I try to do this with Varia my laptop keeps running doing practically nothing after the download is done, which is a bit suboptimal.

For now I am forced to use _wget_ from the command line, chained with _systemctl suspend_ - this works fine for my needs, but I thought I will bring it up here, to see if you may be interested. :)

**Comment by giantpinkrobots** [comment]
Hello. Cool idea for a new feature, and should be possible to implement. It would require more Flatpak permissions in order to be able to shut down the system, which also shouldn't be an issue considering this is a pretty standard feature in a lot of download managers.

**Comment by giantpinkrobots** [comment]
I added this feature with the newest v2024.3.20 update. Thanks for the suggestion!
