### ISSUE TITLE
Download categories 

### ISSUE THREAD

**Issue by wada3n** [giantpinkrobots/varia#8]
I think the app should be used to automatically organize downloads using specific download categories.
![Categorise](https://github.com/giantpinkrobots/varia/assets/13304792/25a6f7de-bae6-4057-93d9-12bb1e816647)

I think the best place for that is the side bar.
Above on the side, a plus icon can be added to enable the user to insert a new URL.

**Comment by wada3n** [comment]
Well, the idea is not only related to categories such as tags, for example, but it extends to the download categories themselves, meaning downloads that are stopped, those that contain errors, those that have finished, those that are waiting to be downloaded at a later time (Download Queues), and so on, and they are not related to the file manager, but rather to download management.

**Comment by bragefuglseth** [comment]
I see, but as I said a popover menu should be enough for that.

**Comment by giantpinkrobots** [comment]
Hello. I forgot to write to this issue.
Buttons for viewing just the items being downloaded or have completed downloading were already added, but I now added two more buttons: Seeding and Failed.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/f31dbcbe-b9b8-46b0-99b1-7f546ceabae7)

I think it's still not cluttered after adding these buttons. I will make this available with a new push to the next branch, and will be released with the next version.

But if we're going to have tags and file type categories, I agree with bragefuglseth that it would really clutter-up the sidebar. Some other design idea would be needed.

**Comment by wada3n** [comment]
I think this is quite enough.

**Comment by giantpinkrobots** [comment]
Released with v2024.5.7.
