### ISSUE TITLE
[Feature] Add option to download with server timestamp

### ISSUE THREAD

**Issue by ZorinFoss** [giantpinkrobots/varia#85]
Hi,

First of all, i really appreciating your efforts in developing `varia`.

As `varia` is a GUI to aria, downloading with server timestamp can be achieved by adding this option
![varia](https://github.com/giantpinkrobots/varia/assets/132728893/30f0a3e3-2be5-4d73-aea4-3063bdcdb014)

Thanks,

**Comment by giantpinkrobots** [comment]
Should be easy to implement. Adding it to the to do list.

**Comment by giantpinkrobots** [comment]
Alright, it is done. It will be available with the next version. Thanks for the suggestion.

**Comment by ZorinFoss** [comment]
> Alright, it is done. It will be available with the next version. Thanks for the suggestion.

Thank you :+1:
