### ISSUE TITLE
Login and use Authentication

### ISSUE THREAD

**Issue by wada3n** [giantpinkrobots/varia#9]
Please can you add a possibility of setting a username and password for downloading.

![login](https://github.com/giantpinkrobots/varia/assets/13304792/1133ff71-7feb-4edf-8151-780faed57282)

**Comment by giantpinkrobots** [comment]
Will be added with the next commit.

![screenshot](https://github.com/giantpinkrobots/varia/assets/93845996/0b0dfcae-0b76-4b08-b600-c3e28aec7a85)
