### ISSUE TITLE
Add presets bestaudio, worstvideo, --cookies-from-browser....

### ISSUE THREAD

**Issue by trimechee** [giantpinkrobots/varia#92]
Hello, thank you for this awesome efficient downloader ! 💯 🥇 

Pleasei have request : for exemple we hope to download quickly only audio from youtube videos poscasts, so it will be great to even more speed up and simplify the process of adding presets worstaudio, bestaudio, worstvideo, bestvideo, option to download directly quick medium video resolution, -f worstaudio -x,
-f bestaudio -x, and adding cookies preset if there is problem with downloading video from facebook for example.....: --cookies-from-browser firefox....

Thank you so much !

**Comment by giantpinkrobots** [comment]
Irrelevant for now as there is no video download functionality in Varia. But I did add an option to import a cookies.txt file in the commit [56b4284fee25242454db1eadbde9ba5da0032bbe](https://github.com/giantpinkrobots/varia/commit/56b4284fee25242454db1eadbde9ba5da0032bbe).
