### ISSUE TITLE
Exit, hibernate, shutdown after downloads finsih

### ISSUE THREAD

**Issue by trimechee** [giantpinkrobots/varia#96]
Hello, It will be great please if there is option "exit" after all downloads finsih, and "hibernate" and "shutdown" option after all download complete because some files are too big and it takes a lot of time to finish downloads ot files which weighs many gigabyte and these options help save battery and energy and ecology....thank you so much !

**Comment by giantpinkrobots** [comment]
Exit after completion functionality was added with the commit [5f0980e63a3a048fe28ec5fc991d17f32e5872d7](https://github.com/giantpinkrobots/varia/commit/5f0980e63a3a048fe28ec5fc991d17f32e5872d7). Shutdown functionality already exists as of v2024.3.20. I don't plan on adding a hibernate after completion function as very few people would even care about it and it's not even available by default on many Linux systems. Maybe if more people ask for it? But for now I'll close this.
